

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(555, 518)
        signup.setStyleSheet("background-color: rgb(255, 74, 38);")
        self.centralwidget = QtWidgets.QWidget(signup)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setMaxLength(40)
        self.name.setObjectName("name")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.name)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.emailid = QtWidgets.QLineEdit(self.centralwidget)
        self.emailid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.emailid.setMaxLength(40)
        self.emailid.setObjectName("emailid")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.emailid)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.male = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.male.setFont(font)
        self.male.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.male.setObjectName("male")
        self.horizontalLayout.addWidget(self.male)
        self.female = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.female.setFont(font)
        self.female.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.female.setObjectName("female")
        self.horizontalLayout.addWidget(self.female)
        self.other = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.other.setFont(font)
        self.other.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.other.setObjectName("other")
        self.horizontalLayout.addWidget(self.other)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(9, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.mobile = QtWidgets.QLineEdit(self.centralwidget)
        self.mobile.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mobile.setMaxLength(10)
        self.mobile.setObjectName("mobile")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.mobile)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.addresss = QtWidgets.QTextEdit(self.centralwidget)
        self.addresss.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.addresss.setObjectName("addresss")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.addresss)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(17, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.password2 = QtWidgets.QLineEdit(self.centralwidget)
        self.password2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password2.setMaxLength(32)
        self.password2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2.setObjectName("password2")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.password2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout.setLayout(20, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.submit.setObjectName("submit")
        self.horizontalLayout_4.addWidget(self.submit)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.formLayout.setLayout(22, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_6)
        signup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(signup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        signup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(signup)
        self.statusbar.setObjectName("statusbar")
        signup.setStatusBar(self.statusbar)

        self.retranslateUi(signup)
        self.pushButton_2.clicked.connect(self.password2.clear)
        self.pushButton_2.clicked.connect(self.emailid.clear)
        self.pushButton_2.clicked.connect(self.name.clear)
        self.pushButton_2.clicked.connect(self.addresss.clear)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "Submit Page"))
        self.label_4.setText(_translate("signup", "EMAIL ID"))
        self.label_3.setText(_translate("signup", "GENDER"))
        self.male.setText(_translate("signup", "MALE"))
        self.female.setText(_translate("signup", "FEMALE"))
        self.other.setText(_translate("signup", "OTHER"))
        self.label_7.setText(_translate("signup", "MOBILE"))
        self.label_2.setText(_translate("signup", "ADDRESS"))
        self.label_5.setText(_translate("signup", "PASSWORD"))
        self.submit.setText(_translate("signup", "SUBMIT"))
        self.pushButton_2.setText(_translate("signup", "RESET"))
        self.label.setText(_translate("signup", "FULL NAME"))
        self.label_6.setText(_translate("signup", "            SIGNUP PAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signup = QtWidgets.QMainWindow()
    ui = Ui_signup()
    ui.setupUi(signup)
    signup.show()
    sys.exit(app.exec_())

